Pipeline

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -34,7 +34,7 @@ jobs:
         with:
           context: .
           push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/bookstagram-backend:latest
+          tags: ${{ secrets.DOCKER_USERNAME }}/Jaimy-sales-backend:latest
 
       # Step 7: Setup SSH for EC2
       - name: Setup SSH for EC2
@@ -61,32 +61,36 @@ jobs:
             fi
             
             echo 'Pulling Docker image...'
-            docker pull ${{ secrets.DOCKER_USERNAME }}/bookstagram-backend:latest || { echo 'Docker pull failed'; exit 1; }
+            docker pull ${{ secrets.DOCKER_USERNAME }}/Jaimy-sales-backend:latest || { echo 'Docker pull failed'; exit 1; }
     
             echo 'Stopping existing container...'
-            docker stop bookstagram-backend || true 
-            docker rm bookstagram-backend || true
+            docker stop Jaimy-sales-backend || true 
+            docker rm Jaimy-sales-backend || true
     
             echo 'Running new container...'
-            docker run -d -p 8000:8000 --name bookstagram-backend \
+            docker run -d -p 8000:8000 --name Jaimy-sales-backend \
               -e MONGO_URL='${{ secrets.MONGO_URL }}' \
               -e PORT='${{ secrets.PORT }}' \
-              -e NEXT_PUBLIC_APP_URL='${{ secrets.NEXT_PUBLIC_APP_URL }}' \
+              -e HUBSPOT_CLIENT_SECREAT='${{ secrets.HUBSPOT_CLIENT_SECREAT }}' \
+              -e HUBSPOT_API_KEY='${{ secrets.HUBSPOT_API_KEY }}' \
+              -e HUBSPOT_FORM_GUIDS='${{ secrets.HUBSPOT_FORM_GUIDS }}' \
+              -e BACKEND_URL='${{ secrets.BACKEND_URL }}' \
+              -e WHATSAPP_API_URL='${{ secrets.WHATSAPP_API_URL }}' \
               -e RESEND_API_KEY='${{ secrets.RESEND_API_KEY }}' \
               -e COMPANY_RESEND_GMAIL_ACCOUNT='${{ secrets.COMPANY_RESEND_GMAIL_ACCOUNT }}' \
-              -e ACCOUNTSID='${{ secrets.ACCOUNTSID }}' \
-              -e AUTHTOKEN='${{ secrets.AUTHTOKEN }}' \
-              -e FROMPHONENUMBER='${{ secrets.FROMPHONENUMBER }}' \
+              -e WHATSAPP_PHONE_NUMBER_ID='${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}' \
+              -e WHATSAPP_VERIFY_TOKEN='${{ secrets.WHATSAPP_VERIFY_TOKEN }}' \
+              -e WHATSAPP_ACCESS_TOKEN='${{ secrets.WHATSAPP_ACCESS_TOKEN }}' \
               -e AUTH_SECRET='${{ secrets.AUTH_SECRET }}' \
               -e JWT_SALT='${{ secrets.JWT_SALT }}' \
-              -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
-              -e AWS_REGION='${{ secrets.AWS_REGION }}' \
-              -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
-              -e AWS_BUCKET_NAME='${{ secrets.AWS_BUCKET_NAME }}' \
-              -e TWILIO_PHONE_NUMBER='${{ secrets.TWILIO_PHONE_NUMBER }}' \
-              -e TWILIO_AUTH_TOKEN='${{ secrets.TWILIO_AUTH_TOKEN }}' \
+              -e JWT_SECRET_PHONE='${{ secrets.JWT_SECRET_PHONE }}' \
+              -e FRONTEND_URL='${{ secrets.FRONTEND_URL }}' \
+              -e WEBHOOK_URL='${{ secrets.WEBHOOK_URL }}' \
               -e TWILIO_ACCOUNT_SID='${{ secrets.TWILIO_ACCOUNT_SID }}' \
-              ${{ secrets.DOCKER_USERNAME }}/bookstagram-backend:latest || { echo 'Docker run failed'; exit 1; }
+              -e TWILIO_API_KEY='${{ secrets.TWILIO_API_KEY }}' \
+              -e TWILIO_API_SECRET='${{ secrets.TWILIO_API_SECRET }}' \
+              -e TWILIO_PHONE_NUMBER='${{ secrets.TWILIO_PHONE_NUMBER }}' \
+              ${{ secrets.DOCKER_USERNAME }}/Jaimy-sales-backend:latest || { echo 'Docker run failed'; exit 1; }
 
             echo 'Container running successfully'
     
